### ISSUE TITLE
Relation to zinc.rs?

### ISSUE THREAD

**Issue by tehwalris** [fabricedesre/cc3200-rs#66]
I have not been able to find any discussion about this project and [zinc.rs](https://github.com/hackndev/zinc). Since this project is a hardware and built in network library abstraction for the TI cc3200, wouldn't it be a good fit to integrate this into zinc.rs? 

I'd like to get an idea about why this project is separate from zinc. Obviously I'm not proposing moving anything anywhere right now, but I think it would be good for people like me who come across both this and zinc to understand why they are separate and if they would ever merge.

**Comment by dhylands** [comment]
I played with zinc a bit (and added stm32f7 support). We didn't use zinc for this project because I wasn't aware that zinc supported the cc3200. i.e. if I search the source tree there is no mention of the cc3200 anywhere.

Or were you asking why we didn't add support for the cc3200 to zinc?

I think it's because it would take considerably more effort to make to a pure rust port rather than using the C SDK that TI provides. Which isn't to say that it can't be done, and I think it's probably worth looking at down the road. TI supports FreeRTOS on the cc3200 and we are using freertos_rs. Being relatively new to the cc3200, I felt more comfortable starting with the C code and going that route.

**Comment by tehwalris** [comment]
I was asking why you didn't add cc3200 support to zinc. Your answer explained exactly what I wanted to know, thanks.
